#!/bin/bash
# Usage:
#   download-channels [CHANNEL...]
# Example:
#   download-channels scishow numberphile cgpgrey

TARGET_DOWNLOADS=$HOME/.youtube/downloads

if [ "$(command -v jq)" = "" ]; then
    echo "Could not find jq. Please install it"
    exit -1
fi

if [ "$(command -v youtube-dl)" = "" ]; then
    echo "Could not find youtube-dl. Please install it"
    exit -1
fi

for CHANNEL in "$@"; do
    CHANNEL=$(echo $CHANNEL | tr '[:upper:]' '[:lower:]')

    mkdir -p $TARGET_DOWNLOADS/$CHANNEL

    LINES=`curl --silent "https://www.youtube.com/user/$CHANNEL/videos" \
       --compressed \
       -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' \
       -H 'Accept-Language: en-US,en;q=0.5' -H 'Cache-Control: max-age=0' -H 'DNT: 1' \
       -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0' \
       | grep ytInitialData \
       | head -n 1 \
       | awk -F = '{$1=""; print substr($0, 0, length($0)-1)}' \
       | jq --raw-output '.contents.twoColumnBrowseResultsRenderer.tabs[1]
         .tabRenderer.content.sectionListRenderer.contents[0]
         .itemSectionRenderer.contents[0].gridRenderer.items
         | map(.gridVideoRenderer)
         | map(.videoId + "," + .title.simpleText)
         | join("\n")' \
        | head -n 5`

    while read -r line; do
        ID=$(echo $line | awk -F ',' '{print $1}' | xargs)
        TITLE=$(echo $line | awk -F ',' '{$1=""; print $0}')

        if [ ! -f $TARGET_DOWNLOADS/$CHANNEL/$ID.mp4 ]; then
            printf "[%s] [%s] [%s] %s\n" "$(date +'%Y-%m-%d %H:%M:%S')" "$CHANNEL" "$ID" "$TITLE" >> $TARGET_DOWNLOADS/download.log
            youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4' --write-thumbnail -o "$TARGET_DOWNLOADS/$CHANNEL/$ID" "https://www.youtube.com/watch?v=$ID"
            echo $line >> $TARGET_DOWNLOADS/$CHANNEL/videos.log
        fi
    done <<< "$LINES"

done
